const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const oldOccupancySchema = new Schema({
    level: {
        type: Number,
        required: true
    },
    deskOccupancy: {
        type: Array,
        required: true
    }
});

// const deskObjSchema = new Schema({
//     tableID: {
//         type: Number,
//         required: true
//     },
//     status: {
//         type: String,
//         required: true
//     },
//     expiryTime: {
//         type: String,
//         required: true
//     }
// })

// const newOccupancySchema = new Schema({
//     level: {
//         type: Number,
//         required: true
//     },
//     deskOccupancy: {
//         type: Object
//     }
// })

const newOccupancySchema = new Schema({
    _id: { //need to find a way to replace auto generated id with this
        type: String,
        required: true
    },
    location: {
        type: String,
        required: true
    },
    level: {
        type: Number,
        required: true
    },
    tableNumber: {
        type: Number,
        required: true
    },
    occupancyStatus: {
        type: String,
        required: true
    },
    ExpiryTime: {
        type: String,
        required: true
    }
});

const loggingSchema = new Schema({
    _id: { //replqce _id auto generated by mongodb
        type: String,
        required: true
    },
    location: {
        type: String,
        required: true
    },
    level: {
        type: Number,
        required: true
    },
    tables: {
        type: Array,
        required: true
    }
});

//create a model
const newOccupancy = mongoose.model('Current Occupancy', newOccupancySchema);
const loggingList = mongoose.model('Logging List', loggingSchema);
const oldOccupancy = mongoose.model('Old Occupancy', oldOccupancySchema);


// const table_obj_to_json = (id, status)=>{
//   const data = {
//     "table": id,
//     "status": status
//   }
//   return data
// }

module.exports = {newOccupancy,oldOccupancy,loggingList}